spring.application.name=revshop
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.username=revshop
spring.datasource.password=revshop

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.upload.root-dir=uploads
app.upload.product-images-dir=uploads/product-images
app.upload.profile-images-dir=uploads/profile-images
app.upload.public-base-url=http://localhost:8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

app.admin.api-key=revshop-admin-2026

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha


# Razorpay checkout
#razorpay.key-id=${RAZORPAY_KEY_ID:}
razorpay.key-id=rzp_test_SWIINPSf9mdUKu

#razorpay.key-secret=${RAZORPAY_KEY_SECRET:}
razorpay.key-secret=fSAKQjYSC6vTDiULNAwgIST8

razorpay.currency=INR
razorpay.success-url=${RAZORPAY_SUCCESS_URL:http://localhost:8080/buyer/payment-success}
razorpay.cancel-url=${RAZORPAY_CANCEL_URL:http://localhost:8080/buyer/payment-cancel}
razorpay.company-name=RevShop
razorpay.company-logo=
razorpay.theme-color=#0d6efd


# Detailed application logging
logging.level.root=INFO
logging.level.com.revshop=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
